spring.jpa.show-sql=false
logging.level.root=WARN

spring.flyway.locations=classpath:db/migration,classpath:db/migration/prod
spring.flyway.placeholders.bootstrap_admin_username=${AUTH_BOOTSTRAP_ADMIN_USERNAME:}
spring.flyway.placeholders.bootstrap_admin_password_hash=${AUTH_BOOTSTRAP_ADMIN_PASSWORD_HASH:}
spring.flyway.placeholders.bootstrap_admin_role=${AUTH_BOOTSTRAP_ADMIN_ROLE:ADMIN}
